### ISSUE TITLE
dns leaks

### ISSUE THREAD

**Issue by Killer-Awesome-Phantom** [polkaned/dockerfiles#18]
I have a qbittorrent and a squid proxy routed through a expressvpn container and both have dns leaks is there any way to fix this?

**Comment by jaroslawjanas** [comment]
@Killer-Awesome-Phantom 
How did you check for dns leaks? I'd like to do that too and see if I get the same result.

**Comment by plozachm** [comment]
> @Killer-Awesome-Phantom
> How did you check for dns leaks? I'd like to do that too and see if I get the same result.

There are plenty of tools, check on google, here is one example: https://github.com/macvk/dnsleaktest

**Comment by Killer-Awesome-Phantom** [comment]
To check the proxy i used a website like:
- https://www.doileak.com/
- https://www.expressvpn.com/dns-leak-test
- https://www.dnsleaktest.com/results.html

To check the torrent i used:
- https://www.doileak.com/  (WIth the "Activate additional Torrent Tests." checked)

**Comment by jaroslawjanas** [comment]
@Killer-Awesome-Phantom 
Thanks for the response,
If it's of any interest I went with https://github.com/dperson/openvpn-client
they have a docker image. I haven't tested it for DNS leaks but it seems solid.

**Comment by polkaned** [comment]
Hi @Killer-Awesome-Phantom,

There is no DNS leaking with this container, because there is no DNS leaking with expressvpn by design.
The DNS leaking is due to the other softs that are routed through this container.
To have the DNS leaking protection of expressvpn, you need to use the networking of this container for other containers (like the example of Docker Compose in the ReadMe or expressvpn-transmission container).This container is not design to route external traffic.
